#!/bin/bash
set -e
onion compile \
    --lib src \
    --lib vendor/corneltek/cliframework/src \
    --lib vendor/corneltek/getoptionkit/src \
    --lib vendor/corneltek/universal/src \
    --classloader \
    --bootstrap scripts/phprelease.php \
    --executable \
    --output phprelease.phar
mv phprelease.phar phprelease
chmod +x phprelease
